/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/
-- Find total customers by state

SELECT 	state,
		Count(distinct customer_id)as total_customers
from consumer_behaviour
GROUP by state
ORDER by total_customers DESC;

-- Find total customers by gender
SELECT gender,
		count(distinct customer_id)as total_customers
from 	consumer_behaviour
GROUP by gender
order by total_customers DESC;

-- Find total products by platform
select platform,
		count(items_purchased)as total_products
from consumer_behaviour
GROUP by platform
order by total_products DESC;

SET lc_monetary = 'en_IN';

-- What is the average costs in each category?
SELECT category_browsed,
		ROUND(avg(price_original)::numeric,1)as Avg_Cost
from consumer_behaviour
WHERE amount_spent is not null
group by category_browsed
order by Avg_Cost DESC;

SET lc_monetary = 'en_IN';

-- What is the total revenue generated for each category?
SELECT category_browsed,
       '₹' || TO_CHAR(SUM(amount_spent), '9,99,99,999.00') AS total_revenue
FROM consumer_behaviour
WHERE amount_spent IS NOT NULL
GROUP BY category_browsed
ORDER BY SUM(amount_spent) DESC;

-- What is the total revenue generated by each customer?
SELECT customer_id,
		'₹' || TO_CHAR(SUM(amount_spent), '9,99,99,999.00') AS total_revenue
FROM consumer_behaviour
where amount_spent is not null
group by customer_id
order by sum(amount_spent)DESC;

-- What is the distribution of sold items across states?
SELECT state,
		sum(items_purchased)as sold_items
from consumer_behaviour
where items_purchased is not null
group by state
order by sold_items desc;
		


